### ISSUE TITLE
Add a blank line before and after a list of books 

### ISSUE THREAD

**Issue by MinaYimam** [MinaYimam/readinglist#8]
In the ui.py show_books function, print one blank line before and one blank line after the list of books.

Also print a blank line before and after the 'no books' message.

**Comment by fosabdul** [comment]
I finished add a blank line before and after the line of the books in ui.py

**Comment by MinaYimam** [comment]
this is good but can you there is a shorter way to add a line and this is not a space.

**Comment by fosabdul** [comment]
Issue resolved.
